services:
  vue:
    build:
      context: ./front/wtwt
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=toto
      - MONGO_INITDB_ROOT_PASSWORD=tata
    volumes:
      - storage2:/data/bd
    command: mongod

  api:
    build: 
        context: ./fast_api
        dockerfile: Dockerfile
    environment: 
      - MONGODB_CONNSTRING=mongodb://toto:tata@mongodb:27017
    ports:
      - 8585:8585
      
volumes:
  storage2:
    external: true